require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-gitlab-security

AllCops:
  Exclude:
    - '**/assets/**/*'
    - '**/javascript/**/*'
    - '**/views/**/*'
    - '**/bin/**/*'
    - '**/coverage/**/*'
    - '**/db/migrate/*'
    - '**/db/**/schema.rb'
    - '**/log/**/*'
    - '**/public/**/*'
    - '**/storage/**/*'
    - '**/script/**/*'
    - '**/vendor/**/*'
    - '**/tmp/**/*'
    - '**/node_modules/**/*'
  ExtraDetails: true
  NewCops: enable
  TargetRubyVersion: 2.7

Metrics/ParameterLists:
  Enabled: false

# Security checks
Bundler/InsecureProtocolSource:
  Enabled: true
Security/Eval:
  Enabled: true
Security/JSONLoad:
  Enabled: true
Security/MarshalLoad:
  Enabled: true
Security/Open:
  Enabled: true
Security/YAMLLoad:
 Enabled: true

# rubocop-gitlab-security
GitlabSecurity/DeepMunge:
  Enabled: true
GitlabSecurity/JsonSerialization:
  Enabled: true
GitlabSecurity/RedirectToParamsUpdate:
  Enabled: true
GitlabSecurity/SendFileParams:
  Enabled: true
GitlabSecurity/SqlInjection:
  Enabled: true
GitlabSecurity/SystemCommandInjection:
  Enabled: true
GitlabSecurity/PublicSend:
  Enabled: true


# Style
Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always_true

Style/Documentation:
  Enabled: false

Style/ReturnNil:
  Description: 'Use return instead of return nil.'
  Enabled: true

# conflicts with fasterer check
# https://github.com/fastruby/fast-ruby#hash-vs-hashfetch-code
Style/RedundantFetchBlock:
  Enabled: false

# Rspec
Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/MethodLength:
  Max: 15

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false
