version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        RUBY_VERSION: '3.1.2'
        PG_MAJOR: '14'
        NODE_MAJOR: '16'
        YARN_VERSION: '1.22.17'
    command: ./bin/dev
    volumes:
      - .:/app
      - bundle-volume:/usr/local/bundle
    ports:
      - '3000:3000'
    links:
      - db:db
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_PASSWORD: password
      DB_USER: postgres
      REDIS_URL: redis://redis:6379
      REDIS_SIDEKIQ_DB: 1

  db:
    image: postgres:14.5
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/var/lib/redis/data

volumes:
  bundle-volume:
  db-volume:
  redis-data:
